FROM openjdk:17
WORKDIR /app
COPY . /app
##RUN javac DataServer.java
##CMD ["java", "DataServer"]



# Compilar el proyecto
##RUN chmod +x ./gradlew build

# Establecer el comando predeterminado para ejecutar la aplicación
##CMD ["java", "-cp", "build/classes/java/main", "org.example.data_server.DataServer"]