apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-deployment
  template:
    metadata:
      labels:
        app: game-deployment
    spec:
      containers:
        - name: registry
          image: localhost:5000/game-image:latest
          ports:
            - containerPort: 8080